#!/bin/bash

LIB_PATH="$HOME/urja/build/bin/liburja.so"

# Check if the library file exists
if [ ! -f "$LIB_PATH" ]; then
    echo "Error: Dynamic library not found at $LIB_PATH" >&2
    exit 1
fi

LD_PRELOAD="$LIB_PATH" "$@"
